---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=.bandit.yaml
        files: ^pytile/.+\.py$
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        language_version: python3
        files: ^((pytile|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.json"
          - --quiet-level=4
        exclude_types: [json]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - pydocstyle
        files: ^pytile/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies:
          - toml
        files: ^(pytile|tests)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        files: ^pytile/.+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        files: ^((pytile|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
        files: ^script/.+
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
